name: auto linter
on:
  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest

# this step will auto clone the code into current branch into runner
    steps:
      - name: checkout/ clone the code
        uses: actions/checkout@v7
        
      - name: install linter
        run: pip install ruff  
        
      - name: check file for linting
        run: ruff check.
